export const AMENITY = {
  PARKING: "PARKING",
  WASHROOM: "WASHROOM",
  WATER: "WATER",
  FLOODLIGHTS: "FLOODLIGHTS",
  LOCKER_ROOM: "LOCKER_ROOM",
  SEATING: "SEATING",
  CANTEEN: "CANTEEN",
  FIRST_AID: "FIRST_AID",
  WHEELCHAIR_ACCESS: "WHEELCHAIR_ACCESS",
  WIFI: "WIFI",
} as const;

export type Amenity = (typeof AMENITY)[keyof typeof AMENITY];
