export const REPORT_TYPE = {
  CLOSED: "CLOSED",
  FLOODED: "FLOODED",
  UNSAFE: "UNSAFE",
  BROKEN_LIGHTS: "BROKEN_LIGHTS",
  RENOVATION: "RENOVATION",
  NO_WATER: "NO_WATER",
  OVERCROWDED: "OVERCROWDED",
  DAMAGED_SURFACE: "DAMAGED_SURFACE",
} as const;

export type ReportType = (typeof REPORT_TYPE)[keyof typeof REPORT_TYPE];
