export const SPORT_TYPE = {
  BASKETBALL: "BASKETBALL",
  TENNIS: "TENNIS",
  BADMINTON: "BADMINTON",
  FOOTBALL: "FOOTBALL",
  CRICKET: "CRICKET",
  VOLLEYBALL: "VOLLEYBALL",
  TABLE_TENNIS: "TABLE_TENNIS",
  SWIMMING: "SWIMMING",
  ATHLETICS: "ATHLETICS",
  MULTI: "MULTI",
} as const;

export type SportType = (typeof SPORT_TYPE)[keyof typeof SPORT_TYPE];
